name: forms-app
region: sgp

services:
  - name: forms
    github:
      repo: sixps/client-pridehealth
      branch: cmiller/forms-wizard-implementation
      deploy_on_push: true
    source_dir: apps/forms
    dockerfile_path: apps/forms/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

